sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - vendor
    - zf-mkdoc-theme

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - COVERAGE_DEPS="satooshi/php-coveralls"
    - SITE_URL=https://zendframework.github.io/zend-expressive
    - GH_USER_NAME="Matthew Weier O'Phinney"
    - GH_USER_EMAIL=matthew@weierophinney.net
    - GH_REF=github.com/zendframework/zend-expressive.git
    - secure: "djSWIzje6Y+r72owunmsiCxNlXm1pmnlwMdjhy3L8g9lSnShC7MFvHBhhvEBQgVkKIxjmzq6RPI5wH/+LcotsHsM+LgVsgNhr9B9OR82Y3BNZM+bCU6qKmLWKn2bFafF097VBt22VaggFFlJhifWdCHZ65xfBIXXEACTDLm1nbOL9aKryEpsGTyd/NUyRLPyc9ShoVgHo/6I+NXHGbADxLGokdnQDw4kUpjWs++/G490OrkY8rZHDD2TpCcPca/v7i1+RrJVLnFVhXBAzSmxFLQon+FVN6orhiONs9r8u/sNovQtAEpaO4hmn8LFrf0oK/d4CgNdvm+1CQt+3TWJOM/yqYxOVxB9WukWfeGLn1d/XZvr9pUuF1BAP0r1kd95ewXgSwG9H5CCSBer39c+NnVTHE0PHUSaL0YX5VuOlAJ9K/suxHkRzQroJkkx34hI7EsJYsoMXrxBll7t5l9J8EQNGeihMc81pBWS262PyAlJxDtZ3aJpoVhhrVRpBdKNhXPFi5/nBb8EFxQUIAzYOSPJjbzJZxNBfB13Mq9Qn9WeEtw25QnHY60FmiVTs7hPCuMFOnUrJD+dW4Rkj86GBMecihdB/8TfYFvr6742rMZ+x6KhbyGOJADhp06YJC/2zPfpGzvWR8QqGDfDhXQAS7QNj/yH72OVIwUkC4oePfI="

matrix:
  include:
    - php: 5.6
      env:
        - DEPS=lowest
    - php: 5.6
      env:
        - DEPS=locked
        - TEST_COVERAGE=true
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 5.6
      env:
        - DEPS=latest
    - php: 7
      env:
        - DEPS=lowest
    - php: 7
      env:
        - DEPS=locked
        - CS_CHECK=true
    - php: 7
      env:
        - DEPS=latest
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=locked
    - php: 7.1
      env:
        - DEPS=latest
    - php: hhvm
      env:
        - DEPS=lowest
    - php: hhvm
      env:
        - DEPS=locked
    - php: hhvm
      env:
        - DEPS=latest
  allow_failures:
    - php: hhvm

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - travis_retry composer self-update

install:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer license-check ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then wget -O theme-installer.sh "https://raw.githubusercontent.com/zendframework/zf-mkdoc-theme/master/theme-installer.sh" ; chmod 755 theme-installer.sh ; ./theme-installer.sh ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer upload-coverage ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./zf-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false
